### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by kcleung** [sicreative/VoltageShift#12]
I am using OS X 10.14.2.  When I tried to run the following in the voltageshift directory:

xcodebuild -target VoltageShift.kext

It says:

xcodebuild: error: The project 'VoltageShift.xcodeproj' does not contain a target named 'VoltageShift.kext'.

**Comment by JerryShih** [comment]
Try 
`
xcodebuild -list
`
to list all target names.

**Comment by JerryShih** [comment]
So, I built both voltageshift and Voltageshift instead.

**Comment by markfarnell** [comment]
Thanks!  so should we updated the documentation?

Also, when I try to build, it now fails with:

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "7698T37TAB" with a private key was found. (in target 'VoltageShift')

Build system information
warning: no rule to process file '/Users/abc/git/dev/VoltageShift/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'VoltageShift')

** BUILD FAILED **


how can I solve this problem?

**Comment by vaddieg** [comment]
Open the xcodeproj file in Xcode and in Target settings choose 'Automatic Signing' -> <Your apple id> personal Team for both build targets

**Comment by vaddieg** [comment]
> When I ran:
> 
> xcodebuild -list
> 
> it shows:
> 
> Information about project "VoltageShift":
> Targets:
> VoltageShift
> voltageshift
> 
> ```
> Build Configurations:
>     Debug
>     Release
> 
> If no build configuration is specified and -scheme is not passed then "Release" is used.
> 
> Schemes:
>     voltageshift
>     VoltageShift
> ```
> so the kext is not a target at all.

Camel-cased VoltageShift is a kext target

**Comment by kcleung** [comment]
Thanks heaps!  Now it compiles successfully.  However, when I run:

./voltageshift info

it returns nothing:

MacBook-Pro:Release abc$ ./voltageshift info
Password:
MacBook-Pro:Release abc$ 

So what went wrong?

I am using MacBook Pro Retina late 2013, installed with OS X 10.14.2

**Comment by JerryShih** [comment]
Update the group setting for VoltageShift.kext folder.
`sudo chown -R root:wheel VoltageShift.kext`

**Comment by luismiguelbravo** [comment]
Hello.
I can compile this, did you actualizate de readme.md?
Can you add a video with the installation?
