### ISSUE TITLE
Doesn't work for mac 2018 (mac os:10.13.6)

### ISSUE THREAD

**Issue by JerryShih** [sicreative/VoltageShift#13]
I try this tool with mac 2018(i7-8850h), but the offset is always 0.
```

sudo ./voltageshift offset -75 -50 -75
--------------------------------------------------------------------------
VoltageShift offset Tool
--------------------------------------------------------------------------
Before CPU voltageoffset: 0mv
Before GPU voltageoffset: 0mv
Before CPU Cache: 0mv
--------------------------------------------------------------------------
After CPU voltageoffset: 0mv
After GPU voltageoffset: 0mv
After CPU Cache: 0mv
--------------------------------------------------------------------------
```

**Comment by dvdsosa** [comment]
I have the same issue on an Intel i7-8559U (MBP 2018 13")

**Comment by sicreative** [comment]
Apple locked the overclock function, as new version will showed OC_LOCKED on info:
for example:
./voltageshift info
CPU BaseFreq: 2600, CPU MaxFreq(1/2/4/6): 4300/4200/4100/4000 (mhz) 
OC_Locked  PL1: 100W PL2: 125W 
CPU Freq: 1.3ghz, Voltage: 0.7201v, Power:pkg 3.17w /core 1.11w,Temp: 50 c

**Comment by xiaxichen** [comment]
this my info. how i unlock the OC_Locked 
 voltageshift % ./voltageshift info
------------------------------------------------------
   VoltageShift Info Tool
------------------------------------------------------
CPU voltage offset: 0mv
GPU voltage offset: 0mv
CPU Cache voltage offset: 0mv
System Agency offset: 0mv
Analogy I/O: 0mv
OC mailbox cmd failed
Digital I/O: 0mv
CPU BaseFreq: 2200, CPU MaxFreq(1/2/4/6): 4100/4100/4000/3900 (mhz)
OC_Locked  PL1: 100W PL2: 125W
CPU Freq: 1.3ghz, Voltage: 0.7926v, Power:pkg 9.51w /core 2.28w,Temp: 66 c
