### ISSUE TITLE
RMBP 11,3 reboot on each use

### ISSUE THREAD

**Issue by Charlyo** [sicreative/VoltageShift#14]
After trying both the already compiled binary and a manual compilation, I've always ended up with forced reboot when trying to execute any of the comands. Currently I'm running macOS 10.12.6 on my 2014 retina macbook pro 11.3

**Comment by Charlyo** [comment]
UPDATE: The reboot is due the reading of MSR 0x637.

**Comment by Skaytacium** [comment]
Hey, same problem here, could you tell me how to fix this and what MSR is? im pretty bad at this kinda stuff and volta isnt really working out for me

**Comment by Skaytacium** [comment]
Nvm, Model specific registers

**Comment by Charlyo** [comment]
> Nvm, Model specific registers

Have you been able to figure out which register code (0x...) do we have to use for our model ??
