### ISSUE TITLE
Instant Kernel Panic on Mojave 10.14.4, Haswell Late 2013 Macbook Pro

### ISSUE THREAD

**Issue by ruslan120101** [sicreative/VoltageShift#17]
Integrated Graphics (no discrete card)

running info or mon results in an instance kernel panic

**Comment by sicreative** [comment]
I am no haswell 2013 machine, could you help to try read those MSR to see which make the kernel panic. Thanks.

./voltageshift read 0x???

 0x606 0x194 0x1a0 0x610 0xce 0x611 0x639 0x637 0x639 0x198 0x1a20x19c

**Comment by shasen1235** [comment]
> I am no haswell 2013 machine, could you help to try read those MSR to see which make the kernel panic. Thanks.
> 
> ./voltageshift read 0x???
> 
> 0x606 0x194 0x1a0 0x610 0xce 0x611 0x639 0x637 0x639 0x198 0x1a20x19c

Hi there!

Mine is 2015 MacBook Pro 2.5GHz+M370x

I have the same kernel panic issue.

As soon as the daemon is loaded(Even it's just monitoring), my MacBook Pro will KP instantly then reboot.

I've tried reading those MSR hex codes, neither of them report anything nor causing KP
<img width="682" alt="螢幕快照 2019-06-07 下午1 37 38" src="https://user-images.githubusercontent.com/47751543/59083346-95b76780-8929-11e9-9306-5f8bc653dd5b.png">

 If there's any info needed to provide, I'm willing to help!

THX

**Comment by Skaytacium** [comment]
Yeah, same issue here. My mac is a mid-2015 one with a 4th gen Haswell i7. It instantly goes into kernel panic and restarts and says - "Your mac shut down because of an issue--". I don't know how to fix this except restore back from an older update. Maybe that could work?

**Comment by Skaytacium** [comment]
Oh yeah and mine also uses its iGPU, so the processor really throttles, any fix except a restore?

**Comment by moravcik94** [comment]
> I am no haswell 2013 machine, could you help to try read those MSR to see which make the kernel panic. Thanks.
> 
> ./voltageshift read 0x???
> 
> 0x606 0x194 0x1a0 0x610 0xce 0x611 0x639 0x637 0x639 0x198 0x1a20x19c

Hello, 
My Macbook Pro 15 Mid 2015 also crashed to kernel panic after ./voltageshift info.
So I've tried read those MSR bytes and It crashes on 0x637 and 0x1a20x19c. What does it mean ? Thank you.

**Comment by liam-b** [comment]
Same issue here, instant kernel panic when running `./voltageshift info` on a 15' Mid 2015 2.8ghz running macOS 10.15.

Result from running `./voltageshift read '0x???'`:
```
RDMSR 0 returns value 0xff
(00000000 00000000 00000000 00000000 00000000 00000000 00000000 11111111)
```

**Comment by DaDerpOfDoom5789** [comment]
Yeah I tried doing that (Im skaytacium) so i just ended up booting into windows and getting throttlestop, and on top of that, i was even able to use my dGPU via an iGPU LCD on the GMUX.

**Comment by sicreative** [comment]
> > I am no haswell 2013 machine, could you help to try read those MSR to see which make the kernel panic. Thanks.
> > ./voltageshift read 0x???
> > 0x606 0x194 0x1a0 0x610 0xce 0x611 0x639 0x637 0x639 0x198 0x1a20x19c
> 
> Hello,
> My Macbook Pro 15 Mid 2015 also crashed to kernel panic after ./voltageshift info.
> So I've tried read those MSR bytes and It crashes on 0x637 and 0x1a20x19c. What does it mean ? Thank you.
0x637 used for calcauate CPU freq by direct read of cpu timer value
We changed the read timer method by read system api, although it may slightly inaccuracy, it should solve the problem which 0x637 may take panic.
