### ISSUE TITLE
MacBook 12 compatibility

### ISSUE THREAD

**Issue by adiif1** [sicreative/VoltageShift#18]
Has anyone tried to use this but after MacBook 12?

**Comment by vaddieg** [comment]
I did. It works with -50 -50 -50, but somehow unstable

**Comment by adiif1** [comment]
What year do you have and what is the difference?

**Comment by vaddieg** [comment]
macbook 2015, nearly +1/2 hour of battery life when watching movies

**Comment by vaddieg** [comment]
another is macbook air 2013, it works with -80 -80 -80, stable, +1 hour battery life, turbo boost isn't throttled anymore
