### ISSUE TITLE
Mac OS 10.15 compatibility

### ISSUE THREAD

**Issue by vaddieg** [sicreative/VoltageShift#20]
Has someone already tested with Catalina?

**Comment by Seanopotamus** [comment]
> Has someone already tested with Catalina?

I'm going to do it in the next few days hopefully so I'll keep you posted. 

I'm running a 2018 15" i7 Hexcore so if yours is similar let me know..

**Comment by mrgame64** [comment]
I have tested it, all I keep getting is "macOS is unable to verify this software for malware", thus it's not working

**Comment by vrgimael** [comment]
I can get it to show the info and even set the power limits on a 2018 i7 2.6Ghz MBP running Catalina but I can't set offset voltages. It simply returns "set to 0x0" when I try.

No idea what's causing this though. Any fixes in sight?

**Comment by vrgimael** [comment]
Anyone else?

**Comment by kbitr** [comment]
As, apparently, there is no solution, yet. How do disable the launchd script, so that OSx doesn't complain every few minutes?

**Comment by floreno** [comment]
For me under 10.15.1 on MacBook Air 2013 it's working like a charm.
Maybe the magic is:
sudo spctl --master-disable

**Comment by sicreative** [comment]
It seen this working on 10.15.
