### ISSUE TITLE
Build failed in Mojave,Xcode 10.3

### ISSUE THREAD

**Issue by GeekZJJ** [sicreative/VoltageShift#22]
System Version: 10.14.6 (18G87)
Xcode Version: 10.3 (10G8)
 I cloned this project and failed to build it, Xcode said:
main.mm:697:46: Use of undeclared identifier 'CLOCK_REALTIME'
It seems that the definition was remove in new MacOS. Any suggestion?

**Comment by vaddieg** [comment]
Try reinstalling Xcode, then launch it at least once to install command-line tools. You will also need to open xcodeproj file in order to update Code signing Team

**Comment by GeekZJJ** [comment]
@vaddieg Thanks for reply. I uninstall Xcode and downloaded a offline installer from Apple. The problem just gone. I think there may be some net issue during last installation which cause above problem.
