### ISSUE TITLE
Any fix for kernel panic on Mojave?

### ISSUE THREAD

**Issue by Skaymish** [sicreative/VoltageShift#25]
Is there any fix except a restore maybe that might stop from getting my mac into KP everytime?

**Comment by Skaytacium** [comment]
Sorry, Here are the specs - Mid 2015, Retina 15" Macbook Pro. Core i7, probably a 4950HQ. The discrete GPU is broken, so I messed around with the NVRAM and PRAM to enable the integrated GPU permanently, resulting in IMMENSE throttling. The discrete GPU was an M370X.

**Comment by mo5214** [comment]
It is likely that the U9300 (Called U8900 in earlier models) GPU power rail chip had a bad solder joint as seen here:
https://www.youtube.com/watch?v=lumJ0cN5oyY (it is shown in the video that hes fixing 2012 model. but the same power IC is there for subsequent a1398 models as well)
