### ISSUE TITLE
[BUG] Can't get registry-entry path Sierra last patch

### ISSUE THREAD

**Issue by Charlyo** [sicreative/VoltageShift#26]
On sierra, execution finishes at `printf("Can't get registry-entry path\n");` inside getService() function on main.

```
ret = IORegistryEntryGetPath(service, kIOServicePlane, path);
	if (ret != KERN_SUCCESS) {
		printf("Can't get registry-entry path\n");
		goto failure;
	}
```

Any idea on how to solve this problem?

**Comment by vaddieg** [comment]
it's not needed for the tool to run. Ignore or comment out the printf
`./voltageshift info
Can't get registry-entry path
------------------------------------------------------
   VoltageShift Info Tool
------------------------------------------------------
WRMSR 150 with value 0x8000001000000000
RDMSR 150 returns value 0xf6a00000
CPU voltage offset: -75mv
WRMSR 150 with value 0x8000011000000000
RDMSR 150 returns value 0x100f6a00000
GPU voltage offset: -75mv
WRMSR 150 with value 0x8000021000000000
RDMSR 150 returns value 0x200f6a00000
CPU Cache voltage offset: -75mv
WRMSR 150 with value 0x8000031000000000
RDMSR 150 returns value 0x30000000000
System Agency offset: 0mv
WRMSR 150 with value 0x8000041000000000
RDMSR 150 returns value 0x40000000000
Analogy I/O: 0mv
WRMSR 150 with value 0x8000051000000000
RDMSR 150 returns value 0x50000000000
Digital I/O: 0mv
CPU BaseFreq: 1900, CPU MaxFreq(1/2/4): 2600/2300/2300 (mhz)  PL1: 100W PL2: 125W 
CPU Freq: 1.3ghz, Voltage: 0.6216v, Power:pkg 4.16w /core 1.20w,Temp: 50 c`
