### ISSUE TITLE
Macbook 12 2017 compatibility?

### ISSUE THREAD

**Issue by adiif1** [sicreative/VoltageShift#28]
I use a 12 2017 and it appears I can't get it to work on this m3-7Y32. Does this tool support kaby lake CPU's?

**Comment by adiif1** [comment]
https://www.insanelymac.com/forum/topic/341394-anvmsr-11-for-catalina-1015/

**Comment by adiif1** [comment]
`------------------------------------------------------
   VoltageShift Info Tool
------------------------------------------------------
WRMSR 150 with value 0x8000001000000000
RDMSR 150 returns value 0x0
CPU voltage offset: 0mv
WRMSR 150 with value 0x8000011000000000
RDMSR 150 returns value 0x0
GPU voltage offset: 0mv
WRMSR 150 with value 0x8000021000000000
RDMSR 150 returns value 0x0
CPU Cache voltage offset: 0mv
WRMSR 150 with value 0x8000031000000000
RDMSR 150 returns value 0x0
System Agency offset: 0mv
WRMSR 150 with value 0x8000041000000000
RDMSR 150 returns value 0x0
Analogy I/O: 0mv
WRMSR 150 with value 0x8000051000000000
OC mailbox cmd failed
RDMSR 150 returns value 0x500000000
Digital I/O: 0mv
CPU BaseFreq: 1200, CPU MaxFreq(1/2/4): 3000/2600/2600 (mhz)OC_Locked  PL1: 49W PL2: 49W 
CPU Freq: 1.3ghz, Voltage: 0.6814v, Power:pkg 1.05w /core 0.45w,Temp: 41 c`

**Comment by sicreative** [comment]
Apple locked the OC capability for newer devices, so the undervolt not work, you only can set the Turbo / PL1 / PL2
