### ISSUE TITLE
No output after on 10.14.6 Hackintosh with version 1.22

### ISSUE THREAD

**Issue by WoadZS** [sicreative/VoltageShift#31]
There is no output except ./ voltageshift, The command ./voltageshift can return the help and version information (VoltageShift Undervoltage Tool v 1.21) 
However there is no any other output with other commands(eg. ./voltageshift info ./voltageshift mon). It looks like:
➜  voltageshift ./voltageshift info
➜  voltageshift 

I have updated the command line tool and kext to 1.22 version and also changed the owner to root:wheel as the instruction mentioned.

BTW 1.20 works well but I have deleted the origin files.

Anyone knows how to solve this and appreciate!

**Comment by kfur** [comment]
maybe because kext loading was failed

**Comment by WoadZS** [comment]
> maybe because kext loading was failed
> try to kextload manually

Thanks, but it does not work, here are the outputs:
```
sudo kextload ./VoltageShift.kext
 failed to load - (libkern/kext) link error; check the system/kernel logs for errors or try kextutil(8).
```
Then I follow the instruction,
```
sudo kextutil ./VoltageShift.kext

 Kext with invalid signatured (-67062) allowed: <OSKext 0x7fa0edd11080 [0x7fffaaff88e0]> { URL = "file:///Users/xxx/Desktop/voltageshift/VoltageShift.kext/", ID = "com.sicreative.VoltageShift" }
 Code Signing Failure: not code signed
Warnings: 
     Personality has no CFBundleIdentifier; the kext's identifier will be inserted when sending to the IOCatalogue: 
        VoltageShiftAnVMSR

Warnings: 
     Personality has no CFBundleIdentifier; the kext's identifier will be inserted when sending to the IOCatalogue: 
         VoltageShiftAnVMSR
 
 Disabling KextAudit: SIP is off
 (kernel) kxld[com.sicreative.VoltageShift]: The super class vtable '__ZTV12IOUserClient' for vtable '__ZTV16AnVMSRUserClient' is out of date. Make sure your kext has been built against the correct headers.
 (kernel) kxld[com.sicreative.VoltageShift]: The super class vtable '__ZTV9IOService' for vtable '__ZTV18VoltageShiftAnVMSR' is out of date. Make sure your kext has been built against the correct headers.
 (kernel) Can't load kext com.sicreative.VoltageShift - link failed.
 (kernel) Failed to load executable for kext com.sicreative.VoltageShift.
 (kernel) Kext com.sicreative.VoltageShift failed to load (0xdc008016).
 (kernel) Failed to load kext com.sicreative.VoltageShift (error 0xdc008016).
 Failed to load /Users/xxx/Desktop/voltageshift/VoltageShift.kext - (libkern/kext) link error.
 Check library declarations for your kext with kextlibs(8).
```
``` 
sudo kextlibs ./VoltageShift.kext 
 For all architectures:
    com.apple.kpi.iokit = 18.7
    com.apple.kpi.libkern = 18.7
 
 For x86_64:
     3 symbols not found in any library kext.
```
Any idea? Thanks! @kfur

**Comment by sicreative** [comment]
boot safe mode ("command-f" when boot up )
Utilities > Terminal
>>>> csrutil enable --without kext

reboot to disable kext sign protection.

**Comment by khoa-nv** [comment]
> boot safe mode ("command-f" when boot up )
> Utilities > Terminal
> 
> > > > > csrutil enable --without kext
> 
> reboot to disable kext sign protection.

I did but it still doesn't work

**Comment by WoadZS** [comment]
@sicreative I have already disabled the SIP before
```
➜  ~ csrutil status
System Integrity Protection status: disabled.
```

**Comment by sicreative** [comment]
[voltageshift.zip](https://github.com/sicreative/VoltageShift/files/4002411/voltageshift.zip)
from the log, i thing you are using before catalina 10.15, as i updated the kext target to 10.15, it may break the previous version support.
I will roll back to 10.12, please help check the attached file is usable and inform here, so i will update the code and package.

**Comment by WoadZS** [comment]
@sicreative Thank you so much, but the file is not working as well. Just the as same as before, ./voltageshift works but not with other extra commands, such as mon, info.
My OS version is 10.14.6, let me know if you need any other information that may helpful.

BTW, 1.20 works before, would mind attache 1.20 file so that I can check if there is anything wrong on my hackintosh.  

```
➜  voltageshift sudo kextutil ./VoltageShift.kext
Kext with invalid signatured (-67050) allowed: <OSKext 0x7fee82c112a0 [0x7fffaaff88e0]> { URL = "file:///Users/XXX/Applications/voltageshift/VoltageShift.kext/", ID = "com.sicreative.VoltageShift" }
Code Signing Failure: code signature is invalid
Warnings: 
    Personality has no CFBundleIdentifier; the kext's identifier will be inserted when sending to the IOCatalogue: 
        VoltageShiftAnVMSR

Warnings: 
    Personality has no CFBundleIdentifier; the kext's identifier will be inserted when sending to the IOCatalogue: 
        VoltageShiftAnVMSR

Disabling KextAudit: SIP is off
(kernel) kxld[com.sicreative.VoltageShift]: The super class vtable '__ZTV12IOUserClient' for vtable '__ZTV16AnVMSRUserClient' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.sicreative.VoltageShift]: The super class vtable '__ZTV9IOService' for vtable '__ZTV18VoltageShiftAnVMSR' is out of date. Make sure your kext has been built against the correct headers.
(kernel) Can't load kext com.sicreative.VoltageShift - link failed.
(kernel) Failed to load executable for kext com.sicreative.VoltageShift.
(kernel) Kext com.sicreative.VoltageShift failed to load (0xdc008016).
(kernel) Failed to load kext com.sicreative.VoltageShift (error 0xdc008016).
Failed to load /Users/XXX/Applications/voltageshift/VoltageShift.kext - (libkern/kext) link error.
Check library declarations for your kext with kextlibs(8).
```

```
➜  voltageshift sudo kextlibs ./VoltageShift.kext 
For all architectures:
    com.apple.kpi.iokit = 18.7
    com.apple.kpi.libkern = 18.7

For x86_64:
    3 symbols not found in any library kext.
```

**Comment by munsuri** [comment]
Same issue here, in a Macbook Pro with 10.14.6:
So I tried to compile it locally (even changing targets, all good) BUT can't be loaded:

For x86_64:

    3 symbols not found in any library kext:
	__ZN12IOUserClient8DispatchE5IORPC
	__ZN9IOService8DispatchE5IORPC
	__ZN15OSMetaClassBase8DispatchE5IORPC

**Comment by sicreative** [comment]
The kext should no change between version 1.2 and 1.22
here is previous complied file 1.20 
[voltageshift_1.2.zip](https://github.com/sicreative/VoltageShift/files/4002554/voltageshift_1.2.zip)

**Comment by kfur** [comment]
@munsuri @WoadZS if you are on macOS Mojave kext must be builded by xcode 10 due to SDK version

**Comment by munsuri** [comment]
@sicreative that last version, 1.20 works fine, thanks! I can toggle now the Turbo and limit the power Watts, great! Sadly the undervolting seems to have been locked in the Intels Apple uses...
@kfur I only have xCode 11. But it compiled successfully... dunno why it complains about linkage just when loading...

**Comment by khoa-nv** [comment]
Doest anyone can set PL1 and PL2 with buildlaunchd? I used 
`sudo ./voltageshift buildlaunchd  -160 0 -160 0 0 0 0 35 60 160` 
but it doesnt work??

**Comment by sicreative** [comment]
> @sicreative that last version, 1.20 works fine, thanks! I can toggle now the Turbo and limit the power Watts, great! Sadly the undervolting seems to have been locked in the Intels Apple uses now...
> @kfur I only have xCode 11. But it compiled successfully... dunno why it complains about linkage just when loading...

I don't know why kext complied under Xcode 11 is not work on previous OSX, however you can use the latest voltage script together with 1.20 kext, just replace the kext to old one under some directory.

**Comment by sicreative** [comment]
> Doest anyone can set PL1 and PL2 with buildlaunchd? I used
> `sudo ./voltageshift buildlaunchd -160 0 -160 0 0 0 0 35 60 160`
> but it doesnt work??

it should work. What message as show when you try?
      ./voltageshift power <PL1> <PL2>

**Comment by khoa-nv** [comment]
This is message when I run that command
![image](https://user-images.githubusercontent.com/54359582/71483815-201ad680-283c-11ea-8db5-d65a70b1cb4f.png)

But after shutdown and login again, the PL1 and PL2 no change
![image](https://user-images.githubusercontent.com/54359582/71483857-57898300-283c-11ea-9e10-55916db80782.png)

Did I use it the wrong way?

**Comment by khoa-nv** [comment]
> @sicreative that last version, 1.20 works fine, thanks! I can toggle now the Turbo and limit the power Watts, great! Sadly the undervolting seems to have been locked in the Intels Apple uses now...
> @kfur I only have xCode 11. But it compiled successfully... dunno why it complains about linkage just when loading...

Can you share your options and buildlaunchd command, please?

**Comment by kfur** [comment]
@khoa-nv try `sudo launchctl load /Library/LaunchDaemons/com.sicreative.VoltageShift.plist`

**Comment by kfur** [comment]
@khoa-nv show your `/Library/LaunchDaemons/com.sicreative.VoltageShift.plist` file

**Comment by khoa-nv** [comment]
> @khoa-nv show your `/Library/LaunchDaemons/com.sicreative.VoltageShift.plist` file

Here bro,
![image](https://user-images.githubusercontent.com/54359582/71500975-2049bf00-289a-11ea-9d99-20d93840743c.png)
I'm using this file
![image](https://user-images.githubusercontent.com/54359582/71500991-35bee900-289a-11ea-9fe4-a3bd0b65e07d.png)

**Comment by sicreative** [comment]
please use the latest version if you want fix the PL1/PL2 when launch.
[(https://drive.google.com/file/d/0Bxfvxkevq9udR3BTdVpCTTRaZjg/view?usp=sharing)]
If you use 10.14 or before, replace the 1.2 kext and this should run.

**Comment by khoa-nv** [comment]
> please use the latest version if you want fix the PL1/PL2 when launch.
> [(https://drive.google.com/file/d/0Bxfvxkevq9udR3BTdVpCTTRaZjg/view?usp=sharing)](url)
> If you use 10.14 or before, replace the 1.2 kext and this should run.

Oh my god, thank you so much. I solved my problem. That because I did wrong way. Thank you so much again.

**Comment by WoadZS** [comment]
@sicreative thank you, as you mentioned, the best way to solve this is use the voltageshift script in 1.22 version and kext of 1.20?

> please use the latest version if you want fix the PL1/PL2 when launch.
> [(https://drive.google.com/file/d/0Bxfvxkevq9udR3BTdVpCTTRaZjg/view?usp=sharing)](url)
> If you use 10.14 or before, replace the 1.2 kext and this should run.

**Comment by sicreative** [comment]
We updated the download page for 10.14 or before.

**Comment by pkoning2** [comment]
Found this when searching for the message, sorry about the duplicate bug report.  But when I tried version 1.2 the kext loads fine (manually with kextutil) but then "voltageshift info" crashes the system.
