### ISSUE TITLE
Killed error

### ISSUE THREAD

**Issue by Alexey336** [sicreative/VoltageShift#34]
Just yesterday i've used this utility without any issue. 
MacBook Air 13" 2015 (Core i5-5250U), macOS 10.15.1

![Снимок экрана 2020-01-18 в 18 40 51](https://user-images.githubusercontent.com/9166661/72666326-14c56000-3a22-11ea-9742-352270ae541b.png)

**Comment by WoadZS** [comment]
I have the same issues, and am using the version which support 10.14 on my HP spectre X360 hackintosh with i7-8550u.

**Comment by Alex0Plays** [comment]
> I have the same issues, and am using the version which support 10.14 on my HP spectre X360 hackintosh with i7-8550u.

Do use both script and kext for 10.14, or only script?

**Comment by mo5214** [comment]
After some digging, It appears to be signature verification issue.
![Screen Shot 2020-01-18 at 8 57 57 PM](https://user-images.githubusercontent.com/5936689/72673868-69260b00-3a35-11ea-9775-69fd1d69a34f.png)

**Comment by WoadZS** [comment]
> > I have the same issues, and am using the version which support 10.14 on my HP spectre X360 hackintosh with i7-8550u.
> 
> Do you use both script and kext for 10.14, or only script?

I am using the files downloaded from the https://sitechprog.blogspot.com/2017/06/voltageshift.html

**Comment by WoadZS** [comment]
> After some digging, It appears to be signature verification issue.
> ![Screen Shot 2020-01-18 at 8 57 57 PM](https://user-images.githubusercontent.com/5936689/72673868-69260b00-3a35-11ea-9775-69fd1d69a34f.png)
> 
> Edit
> Confirmed Codesigning issue. Await Author to Re-sign the utility.
> 
> Temporary Workaround:
> Use stripcodesig utility (google it) to remove the invalid signature of the cli binary. It will run then.
> ![Screen Shot 2020-01-18 at 9 03 56 PM](https://user-images.githubusercontent.com/5936689/72673915-2ca6df00-3a36-11ea-9b97-18830fc976a9.png)
> 
> ![Screen Shot 2020-01-18 at 9 07 13 PM](https://user-images.githubusercontent.com/5936689/72673947-8ad3c200-3a36-11ea-9048-62493b192d65.png)

Temporary Workaround works for me, here is the link for stripcodesig:
https://www.dropbox.com/s/wmeeodg91d1qef2/stripcodesig.zip

Thanks @mo5214 and anyone who has this problem can try this before the official fix.

**Comment by Alex0Plays** [comment]
Thank you @mo5214 for solution. Here is fixed binary file by stripcodesig. Just download it, paste in same folder with VoltageShift.kext and use as normal: https://yadi.sk/d/l2cxoKNB8KgVVg

To make it runnable use `chmod +x voltageshift`

**Comment by ken-can-code** [comment]
I had a slightly different error but thanks! This worked for me.

**Comment by juyaolongpaul** [comment]
Thanks, this works for me too!

**Comment by whenmusicattacks** [comment]
Hello ,after tryng to fix this issue in Mojave, i cannot get voltageshift to work at all even using older version, it will just stop the terminal for a second and do nothing. I tried to remove all the stuff with   " sudo rm -rf /Library/Application Support/VoltageShift/ " and delete the launchd with no success. What else should i do to clean up and start from scratch?

**Comment by tuanla93** [comment]
> Hello ,after tryng to fix this issue in Mojave, i cannot get voltageshift to work at all even using older version, it will just stop the terminal for a second and do nothing. I tried to remove all the stuff with " sudo rm -rf /Library/Application Support/VoltageShift/ " and delete the launchd with no success. What else should i do to clean up and start from scratch?

I have exactly the same issue on Macbook pro 13" 2017 i5, Mojave 10.14.6
Please help.

**Comment by Naaberz** [comment]
I have tried just about every fix trying to get this to work, even with fixed binary file... cannot be opened because the developer cannot be verified.

Anyone got this working?

**Comment by octoviaa** [comment]
> Thank you @mo5214 for solution. Here is fixed binary file by stripcodesig. Just download it, paste in same folder with VoltageShift.kext and use as normal: https://yadi.sk/d/l2cxoKNB8KgVVg
> 
> To make it runnable use `chmod +x voltageshift`

thanks @Alexey336 and @mo5214 the 'stripped' binary work on MBA 2020.

**Comment by Gideon357** [comment]
@Alexey336 @mo5214 this still isnt working on Macbook Pro 2013 running Catalina. `./voltageshift info` does nothing.

**Comment by Gideon357** [comment]
> @Alexey336 @mo5214 this still isnt working on Macbook Pro 2013 running Catalina. `./voltageshift info` does nothing.

@tuanla93 @whenmusicattacks @Naaberz just run `sudo chown -R root:wheel VoltageShift.kext` to fix the permissions.
