### ISSUE TITLE
Nothing changed on 2017 İmac and 2018 MacBook Pro

### ISSUE THREAD

**Issue by sabrican244** [sicreative/VoltageShift#36]
Hi i have 2017 27" iMac (i7-7700K) and 2018 15" MacBook Pro (i7-8750H) both running 10.15.4 Catalina
I want to make an undervolt but i can't want to turn off SİP (csrutil enable --without kext) because some programs are want to csrutil disable status (ex. TotalFinder)
Is there another way to undervolt my computers cpu?

Here is iMac terminal command is there anything i am doing wrong?
<img width="1088" alt="Ekran Resmi 2020-04-08 15 03 14" src="https://user-images.githubusercontent.com/8625875/78782416-a9e54e80-79aa-11ea-9bbb-e8c14d9b3405.png">

**Comment by whenmusicattacks** [comment]
almost all MSR are locked on real macs on Skylake and up

**Comment by sicreative** [comment]
if ./voltageshift mon 
show "OC_Lock" mean Apple restricted the undervolt functions.
