### ISSUE TITLE
Making ACPI Calls

### ISSUE THREAD

**Issue by iamkucuk** [sicreative/VoltageShift#37]
Hello all! First of all thank you for this great tool and tremendous work!

I recently transitioned from Windows-Linux combinations to macOS Catalina with my Asus UX430UNR and totally hackintosh noob. My laptop comes with battery charge threshold by default, and it's controlled by a charging circuit which can be programmed by simple ACPI calls. [An example of how I done it in Linux is in here.](https://wiki.archlinux.org/index.php/ASUS_Zenbook_UX430/UX530#Battery_charge_threshold)

As it can be seen from the link;

Code:
`$ echo "\_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x50" > /proc/acpi/call`

this block makes the appropriate ACPI call and activates the thresholding circuit for the desired threshold level. 

So the thing I wonder is, how this command differs from `./voltageshift write`?

Best wishes...

**Comment by hieplpvip** [comment]
Hi @iamkucuk,

`voltageshift` has nothing to with ACPI. All it does is writing to MSR.

You need to patch your DSDT to call `WRAM` after embedded controller (EC) has been loaded. To do that, add these line to method `_REG` in  device `EC0`:
```
If ((Arg0 == 3) && (Arg1 == 1))
{
  \_SB.PCI0.LPCB.EC0.WRAM(0x3af, 0x50)
}
```

For example, on my laptop it looks like this:
```
Method (_REG, 2, NotSerialized)
{
  If ((Arg0 == 0x03))
  {
    ECFL = Arg1
  }
  If ((Arg0 == 3) && (Arg1 == 1))
  {
    \_SB.PCI0.LPCB.EC0.WRAM(0x3af, 0x50)
  }
}
```

**Comment by iamkucuk** [comment]
@hieplpvip Thanks for the informative and complete answer. You should consider update your repo's wiki with this answer.

**Comment by sicreative** [comment]
thanks for @hieplpvip answered. Sorry as ACPI is out of scope of this project.
