### ISSUE TITLE
No CLI output on 10.13

### ISSUE THREAD

**Issue by realies** [sicreative/VoltageShift#4]
Getting no output when running any command from the compiled binary provided on a mid-2014 15" rMBP with SIP disabled.

**Comment by akotlar** [comment]
Make sure you chmod -R root:wheel VoltageShift.kext

**Comment by hocheung20** [comment]
> Make sure you chmod -R root:wheel VoltageShift.kext

It's `chown -R root:wheel VoltageShift.kext`

**Comment by realies** [comment]
Did not manage to test this on 10.13. Now running `10.14 Beta (18A326h)` and after repeating the steps for disabling kext signing and running `sudo chown -R root:wheel VoltageShift.kext`, `./voltageshift info` still returns nothing.

**Comment by koriwi** [comment]
As long as i dont use offset for the first time, i get normal output from mon.
When i run mon in another terminal and set the offset, i get this error in mon terminal.
https://github.com/sicreative/VoltageShift/blob/6bbba15a18fd3105b73e01318b235dfbd9468570/VoltageShiftAnVMSR/main.mm#L1423
