### ISSUE TITLE
Description of OC mailbox

### ISSUE THREAD

**Issue by hieplpvip** [sicreative/VoltageShift#40]
Hi @sicreative, could you tell me where you found the description of OC mailbox and relating stuff (e.g. voltage offsets)?

Thank you for this awesome tool!

**Comment by sicreative** [comment]
We reference of Intel technical documents that not allow republish to public for the OC Mail parameters. Our project is open sourcing so you can reference of code for detail of how implement.
Also you can reference some linux undervolt tool like this https://github.com/mihic/linux-intel-undervolt is similar.
