### ISSUE TITLE
Official release 🙏

### ISSUE THREAD

**Issue by dimaqq** [sicreative/VoltageShift#41]
**I'm not an expert**
I've cloned the repo, tried to build, changed the settings, changed signing to personal, changed the target to match the os version, `10.15`. So I got it to the point where everything is ready, except:

But of course I can't load the kext because it's not signed by a real developer.

Sadly it's a work mac and it has MDM and I cannot disable the protection mode...

Thus, I'm wondering, what would it take to publish official releases of this kext?
Something that will be trusted by macs?

The summer is here, so it's pertinent now :)

**Comment by sicreative** [comment]
kext without disable protection mode require Apple's approved.
As normally Apple not allow kext tweak of low level CPU params.
Sorry about that this amateur project no plan of submit to Apple.

**Comment by dimaqq** [comment]
I wonder if a limited clone of this project (with power limit, without  undervolt) could get approved 🤔
