### ISSUE TITLE
VoltageShift code signature seems to be revoked

### ISSUE THREAD

**Issue by masnormen** [sicreative/VoltageShift#49]
Hello,

I'd like to report that it seems that the certificate or whatever of VoltageShift is invalidated.

I tried to run VoltageShift but it exits immediately and without explanation. As I checked in dmesg it shows that the executable's code signature is invalid.

![image](https://user-images.githubusercontent.com/3425302/92447198-2346ce80-f1e1-11ea-93e8-064c0ee226c9.png)

I've tried redownloading new files but the message is still the same. This happens from yesterday. Previously VoltageShift works just fine.

**Comment by masnormen** [comment]
Here I attached additional info from system.log in console app

![image](https://user-images.githubusercontent.com/3425302/92447661-b41daa00-f1e1-11ea-8f70-d3415313f6c4.png)

**Comment by alinach120602** [comment]
See https://github.com/sicreative/VoltageShift/issues/34

And use Stripcodesig as described
Cheers

**Comment by masnormen** [comment]
> See #34
> 
> And use Stripcodesig as described
> Cheers

Thank you so much! This worked for me.

I've searched for "SIGKILL" and "terminate" in issues before posting here, but turned out the other post simply used the word "killed"..... smh sorry for duplicate folks.
