### ISSUE TITLE
Noob Needs Help!

### ISSUE THREAD

**Issue by Zephariael** [sicreative/VoltageShift#51]
This is probably an issue with my zsh path but I don't know how to fix. Running:
./voltageshift info

Returns:
zsh: no such file or directory: ./voltageshift

How do I fix this?

Thanks in advance!

**Comment by Drowningfish223** [comment]
You have to cd (think about it as choose directory) into a folder before you can use any of the items in the folder.

So type cd into terminal, then drag and drop the folder with your voltageshift.kext into the terminal. Then you can use any of the voltageshift commands.

**Comment by Drowningfish223** [comment]
Ex: 
cd /Users/usr/Documents/voltageshift

then ./voltageshift.info

**Comment by thisbansal** [comment]
Are you sure you're at the same directory tree? e.g. If your voltageShift is in Downloads folders then you'll need to change directory to Downloads. Which you can easily do with "cd ~/Downloads" command.

figure out where the voltage shift folder is and where you need to navigate in your terminal app.
Hope it helps
