### ISSUE TITLE
Consistent permission issues

### ISSUE THREAD

**Issue by stakeout55** [sicreative/VoltageShift#59]
Hey! To date I have yet to be able to run voltageshift! When I run just `./voltageshift` alone, it runs as it should. If I try and run `./voltageshift info` or any other command (with or without sudo) I get what is seen in the screen shot. I have tried `sudo chown 0:0 voltageshift.kext` and `sudo chown 0:0 voltageshift` to no avail either. Thoughts? Thanks.

<img width="1867" alt="Screen Shot 2020-12-31 at 7 47 24 PM" src="https://user-images.githubusercontent.com/48146384/103431641-61f20180-4ba1-11eb-8357-a0eb358ffab5.png">

**Comment by naveenkrdy** [comment]
@stakeout55 you are doing it wrong.
correct command :
```
sudo chmod -R 0755 VoltageShift.kext
sudo chown -R 0:0 VoltageShift.kext
./voltageshift info
```

**Comment by stakeout55** [comment]
perfect. thank you so much for that!
