### ISSUE TITLE
New CPU Compatibility

### ISSUE THREAD

**Issue by eminSerin** [sicreative/VoltageShift#6]
Thanks for the app. 
I wonder if it works on KabyLake and Coffee Lake chipsets.

**Comment by expresspotato** [comment]
Confirmed not working on CoffeeLake

`bash-3.2# ./voltageshift offset -50 -50
--------------------------------------------------------------------------
VoltageShift offset Tool
--------------------------------------------------------------------------
WRMSR 150 with value 0x8000001000000000
RDMSR 150 returns value 0x0
Before CPU voltageoffset: 0mv
WRMSR 150 with value 0x8000011000000000
RDMSR 150 returns value 0x0
Before GPU voltageoffset: 0mv
--------------------------------------------------------------------------
WRMSR 150 with value 0x80000011f9c00000
WRMSR 150 with value 0x80000111f9c00000
WRMSR 150 with value 0x8000001000000000
RDMSR 150 returns value 0x0
After CPU voltageoffset: 0mv
WRMSR 150 with value 0x8000011000000000
RDMSR 150 returns value 0x0
After GPU voltageoffset: 0mv
--------------------------------------------------------------------------
bash-3.2# 
`

**Comment by stopyan** [comment]
New CPU on Hackintosh Models are avaliable，comfirmed by HP Probook 440 G6 （i5-8265u）， Opencore 0.5.9，OS X Catalina 10.15.5
