### ISSUE TITLE
KMErrorDomain Code=29 Every time I try to run

### ISSUE THREAD

**Issue by adeniji57** [sicreative/VoltageShift#63]
Hi, I have been getting this error for the past week every time I try to run any command in terminal. Any idea what could be causing it? It used to work perfectly but now it doesn't.

![Screenshot 2021-02-14 at 14 36 42](https://user-images.githubusercontent.com/62340017/107878464-2e5e0300-6ed3-11eb-8724-c57ad7ddec14.png)

**Comment by naveenkrdy** [comment]
i think you need to disable SIP and allow the kernel extension in system prefrences -> security & privacy -> general

**Comment by adeniji57** [comment]
I've done both but I still get the error.

**Comment by adeniji57** [comment]
@naveenkrdy The issue actually did end up being SIP-related in the end. I hadn't disabled it properly in config. It's working fine now.

**Comment by jhon12346** [comment]
> @naveenkrdy The issue actually did end up being SIP-related in the end. I hadn't disabled it properly in config. It's working fine now.

i have the exact same problem on macbook pro 15 mid 2015 , how you solved it ?
