### ISSUE TITLE
set MSR on every reboot

### ISSUE THREAD

**Issue by mvoggu** [sicreative/VoltageShift#79]
My Macbook Air 2017's battery is dead and as a result the cpu gets throttled to a frequency of 800MHz.
[`./voltageshift write 0x199 0x1D00`](https://apple.stackexchange.com/a/415982) brings back my cpu performance

So I want to execute the above command automatically on every boot. The problem is, any attempt at running the command automatically(tried using launchd, bash profile) seems to break something and cause the following error from then on (even if executed manually):
`Error Domain=KMErrorDomain Code=71 "Kernel request failed: (libkern/kext) not loadable (reason unspecified) (-603946989)" UserInfo={NSLocalizedDescription=Kernel request failed: (libkern/kext) not loadable (reason unspecified) (-603946989)}`

The error seems to go away only with a clean reinstall of mac os and sometimes also by just rebooting. Any thoughts on why this behaviour occurs or how to set MSR at boot time automatically are appreciated.

Laptop Model Identifier: MacBookAir7,2
OS: macOS Big Sur 11.6
VoltageShift: Version 1.25 binary
SIP state:`csrutil enable --without kext` has been run

**Comment by mvoggu** [comment]
After reading a little about [Controlling kernel extensions](https://eclecticlight.co/2021/07/07/extensions-are-moving-away-from-the-kernel/) on mac os, I tried completely removing and readding voltageshift by:

- unloading kext:
`sudo kmutil unload -p VoltageShift.kext`
- remove voltageshift from my filesystem
`sudo rm -rf /path/to/voltageshift`
- clearing any staged copies of the kext
`sudo kmutil clear-staging`
- clearing Auxiliary Kext Collection (AKC), forcing it to rebuild and require each kernel extension to be re-approved
`kmutil trigger-panic-medic` in mac os recovery mode
- redownload voltageshift binary and use it to set MSR

I do not face the error anymore. I assume the problem was SIP related and `kmutil trigger-panic-medic` + reapproving voltageshift in System Preferences to be what actually solved the problem

**Comment by jozsi** [comment]
Thank you @mvoggu, I had the same issue but got around it using your steps.

On my late 2013 MBP 15 I need to disable TurboBoost and write MSR to disable BD_PROCHOT.

This is how I was able to set the MSR upon every boot & awake from sleep:
1. Create a launchd config that disables TurboBoost, keeps the kext loaded and runs every minute
```
./voltageshift buildlaunchd 0 0 0 0 0 0 0 -1 -1 1 1
```
2. Go to `/Library/Application Support/VoltageShift` and create the following script named `wrapper.sh` (make it executable and chown it to `root:wheel`):
```sh
#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
"$SCRIPT_DIR/voltageshift" $@
"$SCRIPT_DIR/voltageshift" write 0x1FC 0x24005E
```
3. Edit `/Library/LaunchDaemons/com.sicreative.VoltageShift.plist` and replace:
```
<string>/Library/Application Support/VoltageShift/voltageshift</string>
```
with
```
<string>/Library/Application Support/VoltageShift/wrapper.sh</string>
```

The only downside I found, yet, is that takes a maximum of 1 minute after waking up from sleep for the changes to apply.

**Comment by PJayZ** [comment]
Could you run this command automatically on every boot by using launchd, bash profile?
"voltageshift write 0x199 0x1D00"
