### ISSUE TITLE
Does not work on macOS 10.14

### ISSUE THREAD

**Issue by realies** [sicreative/VoltageShift#9]
As per https://github.com/sicreative/VoltageShift/issues/4#issuecomment-410903203

Disabling SIP altogether gives the necessary permissions for voltage modulating apps on macOS Mojave. Unfortunately, VoltageShift causes the machine to restart when calling any of the arguments (info, mon, etc). Nevertheless, the macOS app Volta seems to work fine after `csrutil disable`.

**Comment by osteotek** [comment]
Can confirm the same happening for me on Mojave 18A353d

**Comment by maximejf42** [comment]
work perfect from beta 9 scrutin --without kext --without fs --without internal

**Comment by fabm22** [comment]
Hi there, on the released mojave with SIP disabled (tried with all, kext only), do you guys ACTUALLY see the voltage being applied on your scripts ?   "./voltageshift info"  displays nothing 
Using the Volta licensed app, it does display on the app ui that the voltage changes but it does not *look* like it applied if I try to run some heavy tasks. Would be great if ./voltageShift info would work

**Comment by marianvlaza** [comment]
You need to change the file permissions by running the following command in terminal:
**sudo chown -R root:wheel VoltageShift.kext**

It worked for me after this command.

[https://www.insanelymac.com/forum/topic/331775-guide-how-to-undervolt-your-haswell-and-above-cpu/](url)

**Comment by realies** [comment]
Retried on latest Mojave Pubic Beta 2 (18E184e) with SIP disabled. The kext is owned by `root:wheel` and any command to `voltageshift` other than the help command produces a kernel panic & reboot.

**Comment by Charlyo** [comment]
@realies try to debug yourself the code. Some MSR readings might get you into kernel panic. Mine failed trying to read 0x637

**Comment by chinmayjade** [comment]
I can confirm that it doesn't work on 10.14 mojave (hackintosh).
After `csrutil disable` from recovery, Volta starts working though.
